font_family         JetbrainsMono Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size           11.0
force_ltr           no
background_opacity  0.90

shell_integration     enabled

cursor                #f4f4f4
cursor_text_color     #f4f4f4

foreground            #f4f4f4
background            #161616
selection_foreground  #161616
selection_background  #f4f4f4
url_color             #78a9ff

# Blue
color12               #78a9ff
color4                #0f62fe

# Red
color9                #ff8389
color1                #da1e28

# Green
color10               #42be65
color2                #24a148

# Yellow
color11               #f1c21b
color3                #ff832b

# Magenta
color13               #ff7eb6
color5                #ee5396

# Cyan
color14               #2fd3cc
color6                #009d9a
